# Generated by Django 2.0.4 on 2019-02-23 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spanish', models.CharField(max_length=250)),
                ('danish', models.CharField(max_length=250)),
                ('extra', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danish', models.CharField(max_length=500)),
                ('spanish', models.CharField(max_length=500)),
                ('level', models.CharField(choices=[('B', 'BEGINNER'), ('I', 'INTERMEDIATE'), ('A', 'ADVANCED')], default='B', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proverb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spanish', models.CharField(max_length=250)),
                ('danish', models.CharField(max_length=250)),
                ('extra', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Top200Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spanish', models.CharField(max_length=100)),
                ('danish', models.CharField(max_length=100)),
                ('extra', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserDeck',
            fields=[
                ('navn', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spansk', models.CharField(max_length=250)),
                ('dansk', models.CharField(max_length=250)),
                ('user_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ord.UserDeck')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danish', models.CharField(max_length=150)),
                ('extra', models.CharField(blank=True, max_length=200)),
                ('spanish', models.CharField(max_length=150)),
                ('level', models.CharField(choices=[('B', 'BEGINNER'), ('I', 'INTERMEDIATE'), ('A', 'ADVANCED')], default='B', max_length=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ord.Category')),
            ],
        ),
    ]
